# Generated by Django 5.0.1 on 2024-02-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_incomemodel_superuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomemodel',
            name='superuser_id',
        ),
    ]
