# Generated by Django 5.0.1 on 2024-02-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_expenses_superuser_id_incomemodel_superuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='superuser_id',
        ),
    ]
