# Generated by Django 5.0.1 on 2024-02-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_category_superuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(default='--'),
        ),
    ]
