# Generated by Django 5.0.1 on 2024-04-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_expenses_description'),
        ('authentication', '0010_alter_membersmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('superuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.superusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
