# Generated by Django 5.0.1 on 2024-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_superusermodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
