# Generated by Django 5.0.1 on 2024-02-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_membersmodel_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membersmodel',
            old_name='is_superuser',
            new_name='is_super_user',
        ),
    ]
