# Generated by Django 5.0.1 on 2024-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_is_superuser_membersmodel_is_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='otp',
            field=models.CharField(default=100000, max_length=50),
        ),
    ]
