# Generated by Django 5.0.1 on 2024-02-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_membersmodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
